version: '3.6'

services:
  h1:
    build:
      dockerfile: Dockerfile.H1
      context: .
      args:
        PUBLIC_API_TAG: v0.0.6
        FRONTEND_TAG: v1.0.1
    environment:
      - PUBLIC_API_URI=http://h1:20863
      - PRODUCT_API_URI=http://h2:19572
      - PAYMENT_API_URI=http://h3:13427
    ports:
      - 17564:17564
      - 20863:20863
    depends_on:
      - h2

  h2:
    build:
      dockerfile: Dockerfile.H2
      context: .
      args:
        PRODUCT_API_TAG: v0.0.20
    ports:
      - 19572:19572

  h3:
    build:
      dockerfile: Dockerfile.H3
      context: .
      args:
        PAYMENT_API_TAG: v0.0.16
    ports:
      - 13427:13427

  db1:
    build:
      dockerfile: Dockerfile.DB1
      context: .
    ports:
      - 5432:5432