FROM consul:1.11 as consul-build

FROM postgres:14.2

RUN apt-get update && apt-get install -y bash tcpdump strace net-tools iproute2

ENV POSTGRES_USER=dbuser1
ENV POSTGRES_PASSWORD=supersecret
ENV POSTGRES_DB=products

COPY DB1/products.sql /docker-entrypoint-initdb.d/
COPY DB1/db.hcl /register/db.hcl
COPY --from=consul-build /bin/consul /bin/consul 
