ARG PAYMENT_API_TAG
FROM consul:1.11 as consul-build

FROM hashicorpdemoapp/payments:$PAYMENT_API_TAG
ARG PAYMENT_API_TAG

RUN mv ./spring-boot-payments-${PAYMENT_API_TAG:1}.jar ./spring-boot-payments.jar 
COPY --from=consul-build /bin/consul /bin/consul 
COPY H3/payments-api.hcl /register/payments-api.hcl
COPY H3/docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD java -jar -Dserver.port=13427 ./spring-boot-payments.jar 
