ARG PRODUCT_API_TAG
FROM consul:1.11 as consul-build

FROM hashicorpdemoapp/product-api:$PRODUCT_API_TAG

RUN apk add bash tcpdump strace jq

COPY H2/conf.template.json /conf.template.json
COPY H2/product-api.hcl /register/product-api.hcl
COPY H2/docker-entrypoint.sh /
COPY --from=consul-build /bin/consul /bin/consul 

ENV BIND_ADDRESS=:19572
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "/app/product-api" ]