Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder "../src", "/home/src"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  
    vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    
    sudo mkdir /provisionfiles
    cd /provisionfiles
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose    
    
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:katharaframework/kathara
    sudo apt-get update
    sudo apt-get install kathara xterm xauth

    cd ~ 
    git clone https://github.com/KatharaFramework/Kathara-Labs
    tar -xf KatharaGUI-linux-x64.tar.gz
  SHELL
end
