apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
      app: frontend
  template:
    metadata:
      labels:
        service: frontend
        app: frontend
      annotations:
        # prometheus.io/scrape: "true"
        # prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "false"
        ovs.servicemesh.arkadiuss.dev/consul-register: "true"
        ovs.servicemesh.arkadiuss.dev/ovs-cni-network-name: "ovs-net-vlan-hashicups"
        k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "ovs-net-vlan-hashicups",
          "ips": ["10.1.1.5/24"]
        }
]'
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: hashicorpdemoapp/frontend:v1.0.3
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_PUBLIC_API_URL
              value: "/"
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true
            runAsUser: 0