apiVersion: v1
kind: Service
metadata:
  name: static-client
spec:
  selector:
    app: static-client
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        consul.hashicorp.com/connect-inject: 'false'
        ovs.servicemesh.arkadiuss.dev/consul-register: 'true'
        ovs.servicemesh.arkadiuss.dev/upstreams: 'static-server:7666'
        ovs.servicemesh.arkadiuss.dev/ovs-cni-network-name: 'ovs-net-vlan-100'
        k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "ovs-net-vlan-100",
          "ips": ["10.10.10.2/24"]
        }
]'
    spec:
      containers:
        - name: static-client
          image: curlimages/curl:latest
          # Just spin & wait forever, we'll use `kubectl exec` to demo
          command: ['/bin/sh', '-c', '--']
          args: ['while true; do sleep 30; done;']
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: static-client